### ISSUE TITLE
Figure 1-1. Build-Time vs. Run-Time Efficiency

### ISSUE THREAD

**Issue by philiprbrenan** [mickeyl/introduction-to-vala#2]
Figure 1-1. Build-Time vs. Run-Time Efficiency gives the  impression that Perl is slower than Python in both dimensions.  This is not the case in my experience.  Might it be possible to replace this bubble with a generic term such as "scripting languages"  and thereby avoid the contentious issue of which scripting language is the most expressive/fastest etc.?

**Comment by mickeyl** [comment]
Agreed, that might be helpful. I will add this to the backlog of the next edition. Thanks!
