### ISSUE TITLE
Optimistic rather than euphemistic

### ISSUE THREAD

**Issue by philiprbrenan** [mickeyl/introduction-to-vala#5]
You could consider xlib being the native UI toolkit for systems running an
X-Window display server; however xlib is such a low-level library that the
categorization “toolkit” would be very **euphemistic**.

Possible **optimistic** rather than euphemistic?

**Comment by mickeyl** [comment]
I enjoy using one or the other loanword from languages like greek or latin, but perhaps this is the wrong approach in a non-fiction book. I will reconsider this for the next edition. Thanks!
