### ISSUE TITLE
New edition

### ISSUE THREAD

**Issue by knuxbbs** [mickeyl/introduction-to-vala#7]
So, will there be a more recent edition than the one launched in 2019 by Apress?

I read a sample of the book, and I really found it promising.  I was even thinking of buying a printed copy.

Would you recommend that I wait until the next edition is released?

**Comment by henrique-andrade** [comment]
> So, will there be a more recent edition than the one launched in 2019 by Apress?
> 
> I read a sample of the book, and I really found it promising. I was even thinking of buying a printed copy.
> 
> Would you recommend that I wait until the next edition is released?

I have the same doubt. I really appreciate the book but I would like to know about the new edition.

**Comment by mickeyl** [comment]
To my knowledge, there is no new edition planned at this point of time – at least not from my side. While the publisher is of course allowed to continue working on the material without my permission, I would be surprised if they did so without consulting me.

While my main focus area these days has shifted to another programming language, I continue to monitor Vala for changes. To me, it looks like the team is still on the (long and winding) road to 1.0, hence mostly working on bindings and fixing compiler bugs, so I would not expect that the presented material in the book is no longer applicable.

**Comment by henrique-andrade** [comment]
Thanks for updating us about that, @mickeyl! Your book is great and will help me a lot 👏🏼👏🏾👏🏿👏🏽
